app:
  test: This is scrapper application
  scheduler:
    interval: 10000
  database-access-type: jdbc
  use-queue: true
  rabbitMQ:
    exchange: link
    queue: link.queue
    routing-key: link

check-link-interval-minutes: 5

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application.name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/scrapper
    username: postgres
    password: 123456
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  server.port: 8082
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: ["health", "info", "prometheus"]
      base-path: "/"
      path-mapping:
        info: "info"
        health: "health"
        prometheus: "metrics"
  endpoint:
    info.enabled: true
    health.enabled: true
    prometheus.enabled: true
  metrics.tags.application: ${spring.application.name}
