app:
  test: This is bot application
  use-queue: true
  rabbitMQ:
    exchange: link
    queue: link.queue
    routing-key: link

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui

bot:
  token: ${BOT_TOKEN}