name: Build bot

on:
  pull_request:
    paths:
      - 'bot/**'
  push:
    branches:
      - 'main'
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/aslugin/bot:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Add bot token
        run: | 
          sed -i 's/\${BOT_TOKEN}/$BOT_TOKEN/g' ./bot/src/main/resources/application.yml
        env:
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Maven Package
        run: mvn package -pl bot -am

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }} ./bot/

      - name: Push image to container registry
        run: docker push ${{ env.IMAGE_NAME }}
